name: Deploy Portfolio

on:
    # Trigger on push and pull request to main branch
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

    # Allow manual triggering
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'npm'

            - name: Install Dependencies
              run: npm ci

            - name: Build Project
              run: |
                  npm run build
                  npm run export  # Add this if you want to generate static files

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./out # Next.js static export directory
